# Generated by Django 3.2.9 on 2021-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('school_name', models.CharField(db_column='school_name', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='modified_date')),
                ('hit_count', models.PositiveIntegerField(db_column='hit_count', default=0)),
                ('filename', models.CharField(db_column='filename', max_length=64, null=True)),
                ('del_yn', models.IntegerField(db_column='del_yn', default=0)),
            ],
            options={
                'db_table': 'board_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='school_info',
            fields=[
                ('school_ID', models.CharField(db_column='school_ID', max_length=20, primary_key=True, serialize=False)),
                ('school_name', models.CharField(db_column='school_name', max_length=25)),
                ('school_address', models.CharField(db_column='school_address', max_length=100)),
            ],
            options={
                'db_table': 'school_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_ID', models.CharField(db_column='school_ID', max_length=20, unique=True)),
                ('student_ID', models.CharField(db_column='student_ID', max_length=20, unique=True)),
                ('student_group', models.CharField(db_column='student_group', max_length=20, null=True)),
                ('student_name', models.CharField(db_column='student_name', max_length=20)),
                ('student_rn', models.CharField(db_column='student_rn', max_length=14)),
                ('city', models.CharField(db_column='city', max_length=15)),
                ('street_number', models.CharField(db_column='street_number', max_length=15)),
                ('detail_address', models.CharField(db_column='detail_address', max_length=30)),
                ('student_phone', models.CharField(db_column='student_phone', max_length=15)),
                ('student_img', models.CharField(db_column='student_img', max_length=255)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users_user',
            fields=[
                ('school_ID', models.CharField(db_column='school_ID', max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=128)),
                ('last_login', models.DateTimeField(auto_now=True, db_column='last_login')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
